#!/bin/bash

PHPMINVERSION='5.5.0'
PHPVERSION=`php -r "echo phpversion();"`
PHPCORRECTVERSION=`php -r "echo version_compare(phpversion(), '$PHPMINVERSION');"`

GREEN="\033[1;32m"
RED="\033[1;31m"
BLUE="\033[1;34m"
YELLOW="\033[1;33m"
ENDCOLOR="\033[0m"

echo -e "${BLUE}[BEGIN]${ENDCOLOR} Beginning Expert PHP Deployments development build process."
echo

echo -e "${BLUE}[CHECK]${ENDCOLOR} ./config/build.settings exists."
if [ ! -f ./config/build.settings ]
then
    echo -e "${RED}[FAILURE]${ENDCOLOR} The ./config/build.settings file does not exist. Create it from ./app/config/build.settings.template."
    exit 1
fi
echo -e "${GREEN}[OK]${ENDCOLOR} ./config/build.settings exists."
echo

echo -e "${BLUE}[INSTALL]${ENDCOLOR} Installing Composer."
curl -s https://getcomposer.org/installer | php >/dev/null 2>&1
chmod +x composer.phar
echo

echo -e "${BLUE}[INSTALL]${ENDCOLOR} Installing Doctrine Migrations."
wget -qO doctrine-migrations.phar http://github.com/downloads/ericclemmons/migrations/doctrine-migrations.phar
chmod +x doctrine-migrations.phar 
echo

echo -e "${BLUE}[INSTALL]${ENDCOLOR} Installing PHPUnit."
wget -qO phpunit.phar https://phar.phpunit.de/phpunit.phar
chmod +x phpunit.phar
echo

echo -e "${BLUE}[INSTALL]${ENDCOLOR} Installing Phing."
wget -qO phing.phar http://www.phing.info/get/phing-2.6.1.phar
chmod +x phing.phar 
echo

echo -e "${BLUE}[BEGIN]${ENDCOLOR} Building the Expert PHP Deployments project."

if [ ! -d "log" ]; then
    mkdir log
fi

php phing.phar -Dbuild_settings_file=config/build.settings build

echo -e "${GREEN}[FINISHED]${ENDCOLOR} Building the Expert PHP Deployments project."

echo
echo -e "${GREEN}####################################################################${ENDCOLOR}"
echo -e "${GREEN}# [SUCCESS] The Expert PHP Deployments project is ready to go!     #${ENDCOLOR}"
echo -e "${GREEN}####################################################################${ENDCOLOR}"
echo

exit 0
